# Generated by Django 4.1.1 on 2022-10-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='mart/images'),
        ),
    ]
